project:
  type: book
  output-dir: docs
  resources:
    - "**/*.py"

book:
  title: "Echoes"
  subtitle: "Extended Calculator of HOmogEnization Schemes"
  author: "Jean-François Barthélémy"
  cover-image: img/cover.html
  favicon: img/cover.png
  site-url: https://jfbarthelemy.github.io/echoes/
  repo-url: https://github.com/jfbarthelemy/echoes/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  date: last-modified
  sidebar:
    collapse-level: 2
  chapters:
    - index.qmd
    - intro.qmd
    - part: "𝗘𝗹𝗲𝗺𝗲𝗻𝘁𝘀 𝗼𝗳 𝘁𝗲𝗻𝘀𝗼𝗿 𝗰𝗮𝗹𝗰𝘂𝗹𝘂𝘀"
      chapters: 
        - 1_tensor_calculus/kelvin_mandel.qmd
        - 1_tensor_calculus/rot_matrices.qmd
        - 1_tensor_calculus/special_tensors.qmd
        - 1_tensor_calculus/tensor.qmd
    - part: "𝗘𝘀𝗵𝗲𝗹𝗯𝘆 𝗶𝗻𝗰𝗹𝘂𝘀𝗶𝗼𝗻 𝗽𝗿𝗼𝗯𝗹𝗲𝗺"
      chapters:
        - 2_eshelby/eshelby_hill.qmd
        - 2_eshelby/crack_compliance.qmd
    - part: "𝗖𝗼𝗻𝗰𝗲𝗻𝘁𝗿𝗮𝘁𝗶𝗼𝗻 𝗽𝗿𝗼𝗯𝗹𝗲𝗺𝘀"
      chapters:
        - 3_concentration/concentration_tensors.qmd
        - 3_concentration/nlayer_sphere.qmd
        - 3_concentration/crack.qmd
        - 3_concentration/user_inclusion.qmd
    - part: "𝗥𝗩𝗘 𝗮𝗻𝗱 𝗵𝗼𝗺𝗼𝗴𝗲𝗻𝗶𝘇𝗮𝘁𝗶𝗼𝗻 𝘀𝗰𝗵𝗲𝗺𝗲𝘀"
      chapters:
        - 4_schemes/rve.qmd
        - 4_schemes/schemes.qmd
        - 5_cracked_porous/porous_media.qmd
        - 5_cracked_porous/cracked_media.qmd
        - 4_schemes/exercises_schemes.qmd
    - part: "𝗖𝗼𝗺𝗽𝗹𝗲𝘅 𝗺𝗼𝗱𝘂𝗹𝗶 𝗮𝗻𝗱 𝘃𝗶𝘀𝗰𝗼𝗲𝗹𝗮𝘀𝘁𝗶𝗰𝗶𝘁𝘆"
      chapters:
        - 6_viscoelasticity/complex_moduli.qmd
        - 6_viscoelasticity/viscoelasticity_time.qmd
    - part: "𝗗𝗲𝗿𝗶𝘃𝗮𝘁𝗶𝘃𝗲𝘀 𝗮𝗻𝗱 𝗻𝗼𝗻𝗹𝗶𝗻𝗲𝗮𝗿 𝗲𝘅𝘁𝗲𝗻𝘀𝗶𝗼𝗻𝘀"
      chapters:
        - 7_nonlinear/derivatives.qmd
        - 7_nonlinear/nonlinear.qmd
    - part: "𝗔𝗽𝗽𝗹𝗶𝗰𝗮𝘁𝗶𝗼𝗻𝘀"
      chapters:
        - 8_applications/transport.qmd
        - 8_applications/concrete.qmd
        - 8_applications/cement_paste_diffusion.qmd
        - 8_applications/concrete_strength.qmd
        - 8_applications/ageing_creep.qmd
    - references.qmd
    - api.qmd
  appendices:
    - 99_appendices/tensor_algebra.qmd
    - 99_appendices/hill_tensors.qmd
    - 99_appendices/viscoelastic_hill_kernel.qmd
    - 99_appendices/basics_elas.qmd
    - 99_appendices/viscoelastic_laws.qmd
    - 99_appendices/scheme_derivations.qmd

number-depth: 1

tbl-cap-location: bottom

bibliography: echoes.bib
csl: https://www.zotero.org/styles/elsevier-harvard
link-citations: true

format:
  # latex:
  #   pdf-engine: lualatex
  #   mainfont: TeX Gyre Termes X
  #   mathfont: TeX Gyre Termes Math
  #   monofont: TeX Gyre Cursor
  #   sansfont: TeX Gyre Heros
  #   include-in-header: _config/_macros.tex
  html:
    # theme: journal
    theme:
      - brand
      - _config/customjfb.scss
    # css: _config/styles.css
    toc: true
    page-layout: full
    code-overflow: wrap
    code-block-bg: "#EBF1D4"
    code-block-border-left: "#448D60"
    code-fold: true
    code-link: true
    code-tools: false
    echo: true
    html-math-method: mathjax
    fontsize: 90%
    include-in-header:
      - _config/echoes_highlight.html
      - text: |
          <!-- Google tag (gtag.js) -->
          <script async src="https://www.googletagmanager.com/gtag/js?id=G-DF66M2GWRG"></script>
          <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-DF66M2GWRG');
          </script>      
    include-before-body: _config/_macros_html.md
    default-image-extension: html
  # pdf:
  #   documentclass: scrreprt
  #   pdf-engine: lualatex
  #   classoption: DIV=12
  #   papersize: a4
  #   mainfont: TeX Gyre Pagella
  #   sansfont: TeX Gyre Heros
  #   monofont: JuliaMono
  #   # mathfont: TeX Gyre Termes Math
  #   highlight-style: tango
  #   include-in-header:
  #     - _config/_preamble.tex
  #     - _config/_macros.tex
  #   keep-tex: false
  #   default-image-extension: pdf

crossref:
  fig-title: "Fig."
  fig-prefix: "Fig."
  tbl-title: "Tab."
  tbl-prefix: "Tab."
  eq-prefix: ""

editor:
  render-on-save: true

jupyter: python3
execute:
  freeze: auto
  echo: true
  warning: false
  error: false
  keep-ipynb: false
