::: {.content-hidden}
$$
{{< include config/_macros.tex >}}
$$
:::

# Tensor algebra {#sec-tensor_algebra}

## Conventions of tensor algebra {#sec-tensoralgebra_convention}

This appendix presents some conventions regarding tensor algebra in the usual three-dimensional euclidean space $E=\R^3$. In the sequel, tensor components are associated to an orthonormal frame $(\ve{i})_{i=1,2,3}$ so that introducing the notion of tensor variance is useless here. The following presentation relies on the prior knowledge of the definition of tensors as multilinear operators and the classical isomorphism between the euclidean space and its dual through the scalar product
$$\begin{aligned}
\phi\,\colon E & \longrightarrow  E^* \\
       \uv{v} & \longmapsto \uv{v}\cdot\bullet
\end{aligned}$${#eq-scalarprod}
which allows to identify vectors and linear forms.

Consider two tensors $\mathcal{T}$ and $\mathcal{T}'$ of respective orders $p$ and $q$. The tensor product $\mathcal{T}\otimes\mathcal{T}'$ is the $(p+q)$ order tensor decomposed as
$$
\mathcal{T}\otimes\mathcal{T}'=\mathcal{T}_{i_1,\ldots,i_p} \,\mathcal{T}'_{i_{p+1},\ldots,i_{p+q}}\,
\ve{i_1}\otimes\ldots\otimes\ve{i_{p+q}}
$${#eq-otimes}
where Einstein convention of immplicit summation over repeated indices is adopted
and $\ve{i_1}\otimes\ldots\otimes\ve{i_{p+q}}$ is the multilinear form such that^[$\delta_{ij}=1$ if $i=j$ and $0$ if $i\neq j$ (Kronecker symbol)]
$$
(\ve{i_1}\otimes\ldots\otimes\ve{i_{p+q}})(\ve{j_1},\ldots,\ve{j_{p+q}})
=
\delta_{i_1,j_1}\ldots \delta_{i_{p+q},j_{p+q}}
$${#eq-multfom}
The notation $\mathcal{T}\sotimes\mathcal{T}'$ indicates a tensor product followed by a symmetrization over the last index of $\mathcal{T}$ and the first of $\mathcal{T}'$, i.e.
$$
\mathcal{T}\sotimes\mathcal{T}'=
\frac{\mathcal{T}_{i_1,\ldots,i_p} \,\mathcal{T}'_{i_{p+1},\ldots,i_{p+q}}
+
\mathcal{T}_{i_1,\ldots,i_{p+1}} \,\mathcal{T}'_{i_p,\ldots,i_{p+q}}
}{2}
\,\ve{i_1}\otimes\ldots\otimes\ve{i_{p+q}}
$${#eq-sotimes}
It follows that
$$
\uv{u}\sotimes\uv{v}=\frac{\uv{u}\otimes\uv{v}+\uv{v}\otimes\uv{u}}{2}
$${#eq-sotimesuv}
and an example of generalization involving a second-order tensor $\uu{a}$ and vectors $\uv{u}$ and $\uv{v}$ 
$$
\uv{u}\sotimes\uu{a}\sotimes\uv{v}=
\frac{u_i\,a_{jk}\,v_l+u_i\,a_{jl}\,v_k+u_j\,a_{ik}\,v_l+u_j\,a_{il}\,v_k}{4}
\,\ve{i}\otimes\ve{j}\otimes\ve{k}\otimes\ve{l}
$${#eq-sotimesuav}

The simple dot product or contracted product between $\mathcal{T}$ and $\mathcal{T}'$ involves by convention a contraction between the last index of $\mathcal{T}$ and the first of $\mathcal{T}'$, which leads to the $(p+q-2)$ order tensor
$$
\mathcal{T}\cdot\mathcal{T}'=\mathcal{T}_{i_1,\ldots,i_{p-1},{\color{red}k}} \,\mathcal{T}'_{{\color{red}k},i_{p},\ldots,i_{p+q-2}}\,
\ve{i_1}\otimes\ldots\otimes\ve{i_{p+q-2}}
$${#eq-simpledot}

As regards the double dot product, the classical convention consists in consuming the indices going up from the extremities, which means that a first contraction acts as in the simple dot product then a second contraction is performed between the penultimate index of $\mathcal{T}$ and the second one of $\mathcal{T}'$. However and alternate convention adopted here is proposed in [@brisard2014a]^[see [https://sbrisard.github.io/posts/20140219-on_the_double_dot_product.html](https://sbrisard.github.io/posts/20140219-on_the_double_dot_product.html)], which somehow consists in considering that the double contraction operates over the two last indices of $\mathcal{T}$ as a pair and the two first indices of $\mathcal{T}'$ as the corresponding pair. In other words, this operation is such that if $\uu{a}$ and $\uu{b}$ are two second-order tensors and $\uuuu{T}$ is a fourth-order tensor
$$
\uu{a}:\uu{b}=a_{ij}b_{ij}
\quad\textrm{and}\quad
\uuuu{T}:\uu{a}=T_{ijkl}\, a_{kl}\, \ve{i}\otimes\ve{j}
$${#eq-doubledot}
and the transpose tensor $\trans{\uuuu{T}}$ is consistently defined by
$$
\trans{\uuuu{T}}:\uu{a}=\uu{a}:\uuuu{T}
\quad\Leftrightarrow\quad
\left(\trans{\uuuu{T}}\right)_{ijkl}=\left(\uuuu{T}\right)_{klij}
$${#eq-trans4}

Another useful operator introduced in [@brisard2014a] is the modified tensor product denoted by $\boxtimes$. The fourth-order tensor $\uu{a}\boxtimes\uu{b}$ (where $\uu{a}$ and $\uu{b}$ are two second-order tensors) is defined by its operation over any second-order tensor $\uu{p}$ and by its components
$$\begin{aligned}
& (\uu{a}\boxtimes\uu{b}):\uu{p}=\uu{a}\cdot\uu{p}\cdot\trans{\uu{b}}
=a_{ik}\,p_{kl}\,b_{jl}\,\ve{i}\otimes\ve{j}
\\
& \left(\uu{a}\boxtimes\uu{b}\right)_{ijkl}=a_{ik}\,b_{jl}
\end{aligned}$${#eq-boxtimes}

A symmetrized version of $\boxtimes$ denoted by $\sboxtimes$ can also be
introduced. It operates as
$$\begin{aligned}
& (\uu{a}\sboxtimes\uu{b}):\uu{p}=
(\uu{a}\boxtimes\uu{b}):\left(\frac{\uu{p}+\trans{\uu{p}}}{2}\right)
=\uu{a}\cdot\left(\frac{\uu{p}+\trans{\uu{p}}}{2}\right)\cdot\trans{\uu{b}}
\\
& (\uu{a}\sboxtimes\uu{b})_{ijkl}=\frac{a_{ik}\,b_{jl}+a_{il}\,b_{jk}}{2}
\end{aligned}$${#eq-sboxtimes}

It follows from these definitions that the fourth-order identity, as an operator
over second-order tensors, writes \mbox{$\uuuu{1}=\uu{1}\boxtimes\uu{1}$} where
$\uu{1}$ is the second-order identity.
The fourth-order operator allowing to extract the symmetric part of a
second-order tensor writes \mbox{$\uuuu{I}=\uu{1}\sboxtimes\uu{1}$}.
The latter tensor, which obviously complies with the conditions of minor
symmetries, is classically used to play the role of fourth-order identity
operating over symmetric second-order tensors.

Some remarkable relationships result from the previous definitions
$$\begin{aligned}
&(\uu{a}\boxtimes\uu{b}):(\uv{u}\otimes\uv{v})=
(\uu{a}\cdot\uv{u})\otimes(\uu{b}\cdot\uv{v})
&(a) \\
&(\uu{a}\boxtimes\uu{b}):(\uu{c}\boxtimes\uu{d})=
(\uu{a}\cdot\uu{c})\boxtimes(\uu{b}\cdot\uu{d})
&(b) \\
&(\uu{a}\sboxtimes\uu{b}):(\uu{c}\sboxtimes\uu{d})=
\frac{(\uu{a}\cdot\uu{c})\sboxtimes(\uu{b}\cdot\uu{d})+
(\uu{a}\cdot\uu{d})\sboxtimes(\uu{b}\cdot\uu{c})}{2}
&(c) \\
&(\uu{a}\sboxtimes\uu{a}):(\uu{b}\sboxtimes\uu{b})=
(\uu{a}\cdot\uu{b})\sboxtimes(\uu{a}\cdot\uu{b})
&(d) \\
&\trans{(\uu{a}\boxtimes\uu{b})}=\trans{\uu{a}}\boxtimes\trans{\uu{b}}
&(e) \\
&\trans{(\uu{a}\sboxtimes\uu{a})}=\trans{\uu{a}}\sboxtimes\trans{\uu{a}}
\;\textrm{ but }\;
\trans{(\uu{a}\sboxtimes\uu{b})}\neq\trans{\uu{a}}\sboxtimes\trans{\uu{b}}
&(f) \\
&(\uu{a}\boxtimes\uu{b})^{-1}=\uu{a}^{-1}\boxtimes\uu{b}^{-1}
&(g) \\
&(\uu{a}\sboxtimes\uu{a})^{-1}:\uu{p}=(\uu{a}^{-1}\sboxtimes\uu{a}^{-1}):\uu{p}
\;\textrm{ if }\;\trans{\uu{p}}=\uu{p}
\;\textrm{ but }\;
(\uu{a}\sboxtimes\uu{b})^{-1}\neq\uu{a}^{-1}\sboxtimes\uu{b}^{-1}
&(h)
\end{aligned}$${#eq-propboxtimes}

## Kelvin-Mandel convention {#sec-KM}

The Kelvin-Mandel convention allows to write the matrix of a symmetric
second-order
tensor in a given orthonormal frame \mbox{$(\ve{i})_{i=1,2,3}$}
under the form of a vector of $\R^6$
$$
   \Mat(\eps,(\ve{i}))=
   \left(
   \begin{array}{ccc}
   \varepsilon_{11} & \varepsilon_{12} & \varepsilon_{31}\\
   \varepsilon_{12} & \varepsilon_{22} & \varepsilon_{23}\\
   \varepsilon_{31} & \varepsilon_{23} & \varepsilon_{33}
   \end{array}
   \right)
   \mapsto
   \left(
   \begin{array}{c}
   \varepsilon_{11} \\
   \varepsilon_{22} \\
   \varepsilon_{33} \\
   \sqrt{2}\,\varepsilon_{23} \\
   \sqrt{2}\,\varepsilon_{31} \\
   \sqrt{2}\,\varepsilon_{12}
   \end{array}
   \right)
$${#eq-KM2}

The vector of $\R^6$ in (@eq-KM2) corresponds to the components of the second-order tensor $\eps$ in the basis ordered as
$$
\mathcal{B}=\left(
\ve{1}\otimes\ve{1},
\ve{2}\otimes\ve{2},
\ve{3}\otimes\ve{3},
\sqrt{2}\,\ve{2}\otimes\ve{3},
\sqrt{2}\,\ve{3}\otimes\ve{1},
\sqrt{2}\,\ve{1}\otimes\ve{2}
\right)
$${#eq-basisKM}

The tensors of the basis (@eq-basisKM) form an orthonormal frame spanning
the space of symmetric second-order tensors equipped with the double contraction
"$:$" as scalar product. It follows that the double contraction between
symmetric second-order tensors is no other than the classical scalar product of
the corresponding vectors of $\R^6$ written according to the
convention (@eq-KM2).

Moreover a fourth-order tensor with minor symetries
($C_{ijkl}=C_{jikl}=C_{ijlk}$),
which can be seen as a linear operator acting
over symmetric second-order tensors by double contraction, writes in the same
convention under the form of a $6\times 6$ square matrix
(the solid lines separate blocks affected by different factors whereas the
colored components highlight a central block playing a major role in the sequel)
$$
\Mat(\uuuu{C},\mathcal{B})=
   \left(
   \begin{array}{ccc|ccc}
   C_{1111} & C_{1122} & C_{1133} & \sqrt{2}\,C_{1123} & \sqrt{2}\,C_{1131} & \sqrt{2}\,C_{1112} \\
   C_{2211} & C_{2222} & C_{2233} & \sqrt{2}\,C_{2223} & \sqrt{2}\,C_{2231} & \sqrt{2}\,C_{2212} \\
   C_{3311} & C_{3322} & \color{red}C_{3333} & \color{red}\sqrt{2}\,C_{3323} & \color{red}\sqrt{2}\,C_{3331} & \sqrt{2}\,C_{3312} \\
   \hline
   \sqrt{2}\,C_{2311} & \sqrt{2}\,C_{2322} & \color{red}\sqrt{2}\,C_{2333} & \color{red}2\,C_{2323} & \color{red}2\,C_{2331} & 2\,C_{2312} \\
   \sqrt{2}\,C_{3111} & \sqrt{2}\,C_{3122} & \color{red}\sqrt{2}\,C_{3133} & \color{red}2\,C_{3123} & \color{red}2\,C_{3131} & 2\,C_{3112} \\
   \sqrt{2}\,C_{1211} & \sqrt{2}\,C_{1222} & \sqrt{2}\,C_{1233} & 2\,C_{1223} & 2\,C_{1231} & 2\,C_{1212}
   \end{array}
   \right)
$${#eq-KM4}
The result of $\uuuu{C}:\eps$ writes as a classical
matrix-vector product of (@eq-KM4) by (@eq-KM2).

However another way of ordering the tensors of (@eq-basisKM) which proves
useful for the calculation of crack compliance is based on a gathering of
one set of three in-plane and another one of three out-of-plane tensors
(the latter involving $\n=\ve{3}$ assumed to be the normal of the crack and the former not)
$$
\mathcal{B}^*=\Bigg(
\underbrace{
\ve{1}\otimes\ve{1},
\ve{2}\otimes\ve{2},
\sqrt{2}\,\ve{1}\sotimes\ve{2}
}_{\textrm{in-plane}},
\quad
\underbrace{
\ve{3}\otimes\ve{3},
\sqrt{2}\,\ve{2}\sotimes\ve{3},
\sqrt{2}\,\ve{3}\sotimes\ve{1}
}_{\textrm{out-of-plane}}
\Bigg)
$${#eq-basisKM2}
such that the matrix of $\uuuu{C}$ in $\mathcal{B}^*$ is now obtained by
permutations of lines and columns of (@eq-KM4) to give
$$
\Mat(\uuuu{C},\mathcal{B}^*)=
   \left(
   \begin{array}{ccc|ccc}
   C_{1111} & C_{1122} & \sqrt{2}\,C_{1112} & C_{1133} & \sqrt{2}\,C_{1123} & \sqrt{2}\,C_{1131} \\
   C_{2211} & C_{2222} & \sqrt{2}\,C_{2212} & C_{2233} & \sqrt{2}\,C_{2223} & \sqrt{2}\,C_{2231} \\
   \sqrt{2}\,C_{1211} & \sqrt{2}\,C_{1222} & 2\,C_{1212} & \sqrt{2}\,C_{1233} & 2\,C_{1223} & 2\,C_{1231} \\
   \hline
   C_{3311} & C_{3322} & \sqrt{2}\,C_{3312} & C_{3333} & \sqrt{2}\,C_{3323} & \sqrt{2}\,C_{3331} \\
   \sqrt{2}\,C_{2311} & \sqrt{2}\,C_{2322} & 2\,C_{2312} & \sqrt{2}\,C_{2333} & 2\,C_{2323} & 2\,C_{2331} \\
   \sqrt{2}\,C_{3111} & \sqrt{2}\,C_{3122} & 2\,C_{3112} & \sqrt{2}\,C_{3133} & 2\,C_{3123} & 2\,C_{3131}
   \end{array}
   \right)
$${#eq-KM4bis}
One may notice that the bottom right $3\times 3$ block
of (@eq-KM4bis) exactly corresponds to the colored block in (@eq-KM4).

## Walpole basis {#sec-Walpole}

The Walpole basis [@walpole1984] allowing to write any
fourth-order transversely isotropic relatively to a an axis oriented by the unit
vector $\n$ is composed of the six following tensors
built from $\uu{1}_n=\n\otimes\n$
and $\uu{1}_T=\uu{1}-\uu{1}_n$
$$\begin{aligned}
& \uuuu{E}_1=\uu{1}_n\otimes\uu{1}_n
\quad\textrm{ ; }\quad
\uuuu{E}_2=\frac{\uu{1}_T\otimes\uu{1}_T}{2}
&\textrm{ ; }&
\uuuu{E}_3=\frac{\uu{1}_n\otimes\uu{1}_T}{\sqrt{2}}
\quad\textrm{ ; }\quad
\uuuu{E}_4=\frac{\uu{1}_T\otimes\uu{1}_n}{\sqrt{2}}
&(a) \\
& \uuuu{E}_5=\uu{1}_T\sboxtimes\uu{1}_T-\frac{\uu{1}_T\otimes\uu{1}_T}{2}
&\textrm{ ; }&
\uuuu{E}_6=\uu{1}_T\sboxtimes\uu{1}_n+\uu{1}_n\sboxtimes\uu{1}_T
&(b)
\end{aligned}$${#eq-WalpoleBasis}

Any transversely isotropic fourth-order tensor can be decomposed as
$$
{\uuuu{L}} = {\ell}_{1}\,{\uuuu{E}}_{1} + {\ell}_{2}\,{\uuuu{E}}_{2} +
{\ell}_{3}\,{\uuuu{E}}_{3}+ {\ell}_{4}\,{\uuuu{E}}_{4}+ {\ell}_{5}\,{\uuuu{E}}_{5}+
{\ell}_{6}\,{\uuuu{E}}_{6}
$${#eq-decWalpole}

The six parameters can be conveniently gathered in a triplet
composed of
a $2 \times 2$ matrix containing the four first parameters
$\ell_i$ ($1\leq i \leq 4$) and the two last parameters $\ell_5$
and $\ell_6$
$$
\uuuu{L} \equiv \left( L , {\ell}_{5} , {\ell}_{6}
\right) , \quad
L = \left(
      \begin{array}{cc}
        {\ell}_{1} & {\ell}_{3} \\
        {\ell}_{4} & {\ell}_{2} \\
      \end{array}
    \right)
$${#eq-syntWalpole}

Such a synthetic notation allows simple calculations
of products and inverses which consist in classical matrix or scalar products
and inverses
$$\begin{aligned}
& \uuuu{L} : \uuuu{M} \equiv \left( L M , {\ell}_{5} m_5 , {\ell}_{6} m_6
\right)
&(a) \\
& {\uuuu{L}}^{-1} \equiv \left( {L}^{-1} , \frac{1}{{\ell}_{5}} , \frac{1}{{\ell}_{6}}
\right)
&(b)
\end{aligned}$${#eq-calWalpole}
