# Basic problem of elasticity homogenization {#sec-basics_elas}

## System of equations {#sec-basics_elas_sys_eq}

Consider a representative volume element (RVE) $\Omega$ composed of a heterogeneous material. Neglecting body forces in a problem posed at the scale of a RVE is consistent with the fact that the order of magnitude of mechanical effects induced by body forces is in general much lower than that of the macroscopic strain $\E$ or stress $\Sig$ effects accounting for interactions with particles surrounding the RVE (see [@dormieux2006]). The hypothesis of quasi-static equilibrium is also invoked here to write the balance law involving the Cauchy stress field $\sig$
$$
\divu{\sig}=\uv{0} \quad(\Omega)
$${#eq-divsigma}

In the sequel, the small perturbation hypothesis is adopted so that the strain field $\eps$ derives from the displacement one $\uv{u}$ as the symmetrical part of its gradient
$$
\eps=\frac{\graduu{\uv{u}}+\trans{\graduu{\uv{u}}}}{2} \quad(\Omega)
$${#eq-epsgradu}

In the framework of random media homogenization, two types of conditions applied at the boundary $\partial\Omega$ of a RVE $\Omega$ are usually considered:

- *homogeneous strain boundary conditions* corresponding to prescribed displacements $\uv{u}^g$ at $\partial\Omega$
$$
\uv{u}^g=\E\cdot\x \quad(\partial\Omega)
$${#eq-homstrainBC}
It is noticeable that in this case the divergence theorem implies the following relationship between the microscopic and macroscopic strain tensors
$$
<\eps>_{\Omega}=\frac{1}{\lvert \Omega \rvert}\int_\Omega \eps\ud \Omega
=\frac{1}{\lvert \Omega \rvert}\int_{\partial\Omega} \uv{u}\sotimes\n \ud S
=\E
$${#eq-EhomstrainBC}
where the spatial average over a domain $\omega$ is denoted by $<\bullet>_\omega$ and $\n$ is the unit outward normal at the boundary.
The macroscopic stress tensor is then simply defined as the average
$$
\Sig=
<\sig>_{\Omega}=\frac{1}{\lvert \Omega \rvert}\int_\Omega \sig\ud \Omega
$${#eq-ShomstrainBC}

- *homogeneous stress boundary conditions* corresponding to prescribed surface tractions $\uv{T}^g$ at $\partial\Omega$
$$
\uv{T}^g=\Sig\cdot\n \quad(\partial\Omega)
$${#eq-homstressBC}
Now owing to the remarkable identity $(x_i\sigma_{jk})_{,k}=\sigma_{ij}$ resulting from (@eq-divsigma) and the symmetry of $\sig$, the relationship between the microscopic and macroscopic stress is ensured by the divergence theorem
$$
<\sig>_{\Omega}=\frac{1}{\lvert \Omega \rvert}\int_\Omega \sig\ud \Omega
=\frac{1}{\lvert \Omega \rvert}\int_{\partial\Omega} \x\sotimes(\sig\cdot\n) \ud S
=\Sig
$${#eq-ShomstressBC}
The macroscopic stress tensor is then simply defined as the average
$$
\E=
<\eps>_{\Omega}=\frac{1}{\lvert \Omega \rvert}\int_\Omega \eps\ud \Omega
$${#eq-EhomstressBC}

::: {.callout-note}
## Hill lemma

Note that whatever the choice of boundary conditions between (@eq-homstrainBC) and (@eq-homstressBC), the consistency between the microscopic and macroscopic works is ensured by
$$
<\sig:\eps>_{\Omega}
=\frac{1}{\lvert \Omega \rvert}\int_\Omega \sig:\eps\ud \Omega
=\frac{1}{\lvert \Omega \rvert}\int_{\partial\Omega} \uv{u}\cdot\sig\cdot\n \ud S
=\Sig:\E
$${#eq-Hilllemma}
which results from the application of the divergence theorem to $(u_i\sigma_{ij})_{,k}=u_{i,j}\sigma_{ij}=\varepsilon_{ij}\sigma_{ij}$.
:::

The set of equations defining the problem posed on the RVE is finally completed by the local constitutive law relating the strain and stress fields. The hypothesis of linear elasticity is adopted in this part so that
$$
\sig=\uuuu{c}:\eps \quad(\Omega)
$${#eq-Hooke}
where $\uuuu{c}(\x)$ denotes the heterogeneous (positive definite fourth-order) stiffness tensor field satisfying the conditions of minor ($c_{jikl}=c_{ijlk}=c_{ijkl}$) and major ($c_{klij}=c_{ijkl}$) symmetries. The compliance tensor field is introduced as the inverse $\uuuu{s}=\uuuu{c}^{-1}$ in the sense of fourth-order tensors operating over symmetrical second-order tensors.

In short, the system of equations posed on the RVE is given by (@eq-divsigma), (@eq-epsgradu), (@eq-homstrainBC) or (@eq-homstressBC) and (@eq-Hooke).

## Macroscopic stiffness or compliance tensors {#sec-basics_elas_mac_stiff}

Whatever the boundary condition of homogeneous strain or stress type (@eq-homstrainBC) or (@eq-homstressBC), the linearity of the problem allows to invoke the existence of concentration tensors relating the microscopic strain $\eps$ and stress $\sig$ fields to the macroscopic strain $\E$ or stress $\Sig$ tensors
$$\begin{align}
\eps & =  \uuuu{A}_E:\E \\
\sig & =  \uuuu{B}_E:\E \quad\textrm{with}\quad \uuuu{B}_E=\uuuu{c}:\uuuu{A}_E \\
\sig & =  \uuuu{B}_\Sigma:\Sig \\
\eps & =  \uuuu{A}_\Sigma:\Sig \quad\textrm{with}\quad \uuuu{A}_\Sigma=\uuuu{s}:\uuuu{B}_\Sigma 
\end{align}$${#eq-conc}