<!-- <font size="6">
{{< iconify noto building-construction >}} [**Page under construction**]{.orangebox} {{< iconify noto building-construction >}}
</font>
 -->
# Hill polarization tensors {#sec-hill_elas}

The Hill polarization tensors defined in this section are related to an ellipsoid embedded in the whole space $\R^3$. An ellipsoid $\mathcal{E}_{\uu{A}}$ can be defined by an equation such as
$$
\uv{x}\in\mathcal{E}_{\uu{A}}
\quad\Leftrightarrow\quad
\uv{x}\cdot(\trans{\uu{A}}\cdot\uu{A})^{-1}\cdot\uv{x}\leq 1
$$
where $\uu{A}$ is an invertible second-order tensor so that $\trans{\uu{A}}\cdot\uu{A}$ is a positive definite symmetric tensor associated to 3 radii (eigenvalues $a\geq b \geq c$ possibly written $\rho_1 \geq \rho_2 \geq \rho_3$ for convenience) and 3 angles (orientation of the frame of orthonormal eigenvectors $\uv{e}^{\uu{A}}_1, \uv{e}^{\uu{A}}_2, \uv{e}^{\uu{A}}_3$)
$$
\trans{\uu{A}}\cdot\uu{A}=a^2 \uv{e}^{\uu{A}}_1\otimes\uv{e}^{\uu{A}}_1 + b^2 \uv{e}^{\uu{A}}_2\otimes\uv{e}^{\uu{A}}_2 + c^2 \uv{e}^{\uu{A}}_3\otimes\uv{e}^{\uu{A}}_3 = \sum_{i=1}^3 \rho_i^2 \uv{e}^{\uu{A}}_i\otimes\uv{e}^{\uu{A}}_i
$${#eq-ellipsoid}

## Useful integrals

Some integrals useful for further calculations and intimately connected to the Newtonian potential are introduced as

$$\begin{align}
\uu{I}^{\uu{A}} &= \frac{\det{\uu{A}}}{4\pi}
\int_{\norm{\uv{\xi}}=1}
\frac{\uv{\xi}\otimes\uv{\xi}}
{\norm{\uu{A}\cdot\uv{\xi}}^3}\ud S_{\xi}
=
\frac{1}{4\pi}
\int_{\norm{\uv{\zeta}}=1}
\frac{%
(\uu{A}^{-1}\cdot\uv{\zeta})
\otimes
(\uu{A}^{-1}\cdot\uv{\zeta})
}{\norm{\uu{A}^{-1}\cdot\uv{\zeta}}^2}
\ud S_{\zeta}
\\
\uuuu{U}^{\uu{A}} &= \frac{\det{\uu{A}}}{4\pi}
\int_{\norm{\uv{\xi}}=1}
\frac{\uv{\xi}\otimes\uv{\xi}\otimes\uv{\xi}\otimes\uv{\xi}}
{\norm{\uu{A}\cdot\uv{\xi}}^3}\ud S_{\xi}\\
&=
\frac{1}{4\pi}
\int_{\norm{\uv{\zeta}}=1}
\frac{%
(\uu{A}^{-1}\cdot\uv{\zeta})
\otimes
(\uu{A}^{-1}\cdot\uv{\zeta})
\otimes
(\uu{A}^{-1}\cdot\uv{\zeta})
\otimes
(\uu{A}^{-1}\cdot\uv{\zeta})
}{\norm{\uu{A}^{-1}\cdot\uv{\zeta}}^4}
\ud S_{\zeta}
\\
\uuuu{V}^{\uu{A}} &= \frac{\det{\uu{A}}}{4\pi}
\int_{\norm{\uv{\xi}}=1}
\frac{\uv{\xi}\sotimes\uu{1}\sotimes\uv{\xi}}
{\norm{\uu{A}\cdot\uv{\xi}}^3}\ud S_{\xi}
=
\frac{1}{4\pi}
\int_{\norm{\uv{\zeta}}=1}
\frac{%
(\uu{A}^{-1}\cdot\uv{\zeta})
\sotimes
\uu{1}
\sotimes
(\uu{A}^{-1}\cdot\uv{\zeta})
}{\norm{\uu{A}^{-1}\cdot\uv{\zeta}}^2}
\ud S_{\zeta}\\
&=
\frac{\uu{1}\sboxtimes\uu{I}^{\uu{A}}+\uu{I}^{\uu{A}}\sboxtimes\uu{1}}{2}
\end{align}$${#eq-tensIUV}

::: {.callout-note collapse=true} 

## Proof of the change of variable in @eq-tensIUV (click for details)

The proof detailed here is an intrinsic alternative (see [@barthelemyIJSS2016]) to the reasoning in components presented in [@mura1987].

The change of variable in @eq-tensIUV is a bijective transformation of the unit sphere into itself
$$
\uv{\zeta}\mapsto\uv{\xi}=\frac{\uu{A}^{-1}⋅\uv{\zeta}}{\norm{\uu{A}^{-1}⋅\uv{\zeta}}}
\;\Leftrightarrow\;
\uv{\xi}\mapsto\uv{\zeta}=\frac{\uu{A}⋅\uv{\xi}}{\norm{\uu{A}⋅\uv{\xi}}}
$$

The delicate point of the proof is the following result on surface elements
$$
\ud S_{\zeta}
=\frac{\det{\uu{A}}}{\norm{\uu{A}\cdot\uv{\xi}}^3}\,
\ud S_{\xi}
\;\Leftrightarrow\;
\ud S_{\xi}
=\frac{\det{\uu{A}^{-1}}}{\norm{\uu{A}^{-1}\cdot\uv{\zeta}}^3}\,
\ud S_{\zeta}
$$

It is obvious that $\uv{\xi}$ and $\uv{\zeta}$ play symmetrical role by inverting $\uu{A}$.

Let's start by differentiating the transformation relationship yielding
$$
\ud \uv{\xi}=\left(\uu{1}-\uv{\xi}\otimes\uv{\xi}\right)\cdot
\frac{\uu{A}^{-1}}{\norm{\uu{A}^{-1}\cdot\uv{\zeta}}}\cdot\ud\uv{\zeta}
$$
This transformation gradient can be decomposed as the tangent invertible application $\uv{u}\mapsto\frac{\uu{A}^{-1}}{\norm{\uu{A}^{-1}\cdot\uv{\zeta}}}\cdot\uv{u}$ followed by an orthogonal projection over the plane of normal $\uv{\xi}$.

The end of the proof takes advantage of the following remarks:

- the transformation of a surface vector $\ud\uv{S}$ to $\ud\uv{s}$ by the gradient transformation $\uv{X}\mapsto\ud\uv{x}=\uu{F}⋅\ud\uv{X}$ is $\ud\uv{s}=(\det{\uu{F}})\,\trans{\uu{F}}^{-1}⋅\ud\uv{S}$

- as $\uv{\xi}$ and $\uv{\zeta}$ belong to unit spheres, $\ud \uv{S}_{\zeta}=\ud S_{\zeta}\,\uv{\zeta}$ and $\ud \uv{S}_{\xi}=\ud S_{\xi}\,\uv{\xi}$

- the projection of material vectors over the plane of normal $\uv{\xi}$ becomes a projection on the line directed by $\uv{\xi}$ for surface vectors.

It results that
$$
\ud S_{\xi}=\uv{\xi}\cdot\left(\left(\frac{\det{\uu{A}^{-1}}}{\norm{\uu{A}^{-1}\cdot\uv{\zeta}}^3}\right)\,
\left(\norm{\uu{A}^{-1}\cdot\uv{\zeta}}\trans{\uu{A}}\right)\right)\cdot\uv{\zeta}
\ud S_{\zeta}
=
\frac{\det{\uu{A}^{-1}}}{\norm{\uu{A}^{-1}\cdot\uv{\zeta}}^2}\,
\uv{\zeta}\cdot\uu{A}\cdot\uv{\xi}
\ud S_{\zeta}
$$
which ends the proof by observing that $\uv{\zeta}\cdot\uu{A}\cdot\uv{\xi}=\frac{\norm{\uv{\zeta}}^2}{\norm{\uu{A}^{-1}\cdot\uv{\zeta}}}=\frac{1}{\norm{\uu{A}^{-1}\cdot\uv{\zeta}}}$.

:::

By symmetry, it is obvious that $\uu{A}$ (@eq-ellipsoid) and $\uu{I}^{\uu{A}}$ are simultaneously diagonalizable i.e. they share the same eigenvectors:
$$
\uu{I}^{\uu{A}}=I^{\uu{A}}_1\,\uv{e}^{\uu{A}}_1\otimes\uv{e}^{\uu{A}}_1 + I^{\uu{A}}_2\,\uv{e}^{\uu{A}}_2\otimes\uv{e}^{\uu{A}}_2 + I^{\uu{A}}_3\,\uv{e}^{\uu{A}}_3\otimes\uv{e}^{\uu{A}}_3 = \sum_{i=1}^3 I^{\uu{A}}_i\,\uv{e}^{\uu{A}}_i\otimes\uv{e}^{\uu{A}}_i
$${#eq-decI}

The components $I^{\uu{A}}_i$ can be obtained by identification with expressions derived from the Newtonian potential ([@kellogg1929], [@eshelby1957]). They are gathered in @tbl-Ii or recalled a little later in a generic form ([@barthelemyIJSS2016], [@barthelemyIJES2020_hilltrans]).

|      | ellipsoid | prolate spheroid | oblate spheroid | sphere |
|------|------|------|------|------|
|      | $a>b>c$ | $a>b=c$ | $a=b>c$ | $a=b=c$ |
| $I^{\uu{A}}_1 =$ |  $\frac{a\,b\,c}{(a^2-b^2)\sqrt{a^2-c^2}}\left({\cal F}-{\cal E}\right)$    |   $1-2\,I^{\uu{A}}_3$   |  $c\,\frac{a^2\,\arccos{(c/a)}-c\sqrt{a^2-c^2}}{2\left(a^2-c^2\right)^{3/2}}$    |   $\frac{1}{3}$   |
| $I^{\uu{A}}_2 =$ |  $1-I^{\uu{A}}_1-I^{\uu{A}}_3$    |   $I^{\uu{A}}_3$   |  $I^{\uu{A}}_1$    |   $\frac{1}{3}$   |
| $I^{\uu{A}}_3 =$ |  $\frac{a\,b\,c}{(b^2-c^2)\sqrt{a^2-c^2}}\left(\frac{b\sqrt{a^2-c^2}}{a\,c}-{\cal E}\right)$    |   $a\,\frac{a\sqrt{a^2-c^2}-c^2\,\arcosh{(a/c)}}{2\left(a^2-c^2\right)^{3/2}}$   |   $1-2\,I^{\uu{A}}_1$   |   $\frac{1}{3}$   |

: Components $I^{\uu{A}}_i$ {#tbl-Ii .striped .hover .bordered .danger .sm}

where ${\cal F}={\cal F}(\theta,\kappa)$ and ${\cal E}={\cal E}(\theta,\kappa)$ are respectively the elliptic integrals of the first and second kinds (see [@abramowitz1972]) of amplitude and parameter^[${\cal F}(\theta,\kappa)=\int_{\varphi=0}^\theta \frac{\ud\varphi}{\sqrt{1-\kappa^2\,\sin^2\varphi}}$ and ${\cal E}(\theta,\kappa)=\int_{\varphi=0}^\theta \sqrt{1-\kappa^2\,\sin^2\varphi}\,\ud\varphi$]
$$
\theta=\arcsin{\sqrt{1-\frac{c^2}{a^2}}}
\quad;\quad
\kappa=\sqrt{\frac{a^2-b^2}{a^2-c^2}}
$$

Before detailing the components of $\uuuu{U}^{\uu{A}}$ and $\uuuu{V}^{\uu{A}}$ it is convenient to introduce the coefficients $I^{\uu{A}}_{ij}$ in @tbl-Iij adapted from the approach proposed in [@eshelby1957].

|      | ellipsoid | prolate spheroid | oblate spheroid | sphere |
|------|------|------|------|------|
|      | $a>b>c$ | $a>b=c$ | $a=b>c$ | $a=b=c$ |
| $I^{\uu{A}}_{11} =$ | $\frac{1}{3}\left(\frac{1}{a^2}-I^{\uu{A}}_{31}-I^{\uu{A}}_{12} \right)$ | $\frac{1}{3}\left(\frac{1}{a^2}-2\,I^{\uu{A}}_{31} \right)$ | $\frac{1}{4}\left(\frac{1}{a^2}-I^{\uu{A}}_{31} \right)$ | $\frac{1}{5\,a^2}$ |
| $I^{\uu{A}}_{22} =$ | $\frac{1}{3}\left(\frac{1}{b^2}-I^{\uu{A}}_{12}-I^{\uu{A}}_{23} \right)$  | $\frac{1}{4}\left(\frac{1}{c^2}-I^{\uu{A}}_{31} \right)$ | $\frac{1}{4}\left(\frac{1}{a^2}-I^{\uu{A}}_{31} \right)$ | $\frac{1}{5\,a^2}$ |
| $I^{\uu{A}}_{33} =$ | $\frac{1}{3}\left(\frac{1}{c^2}-I^{\uu{A}}_{23}-I^{\uu{A}}_{31} \right)$  | $\frac{1}{4}\left(\frac{1}{c^2}-I^{\uu{A}}_{31} \right)$ | $\frac{1}{3}\left(\frac{1}{c^2}-2\,I^{\uu{A}}_{31} \right)$ | $\frac{1}{5\,a^2}$ |
| $I^{\uu{A}}_{23} = I^{\uu{A}}_{32} =$ | $\frac{I^{\uu{A}}_3-I^{\uu{A}}_2}{b^2-c^2}$ | $\frac{1}{4}\left(\frac{1}{c^2}-I^{\uu{A}}_{31} \right)$ | $\frac{I^{\uu{A}}_3-I^{\uu{A}}_2}{b^2-c^2}$ | $\frac{1}{5\,a^2}$ |
| $I^{\uu{A}}_{31} = I^{\uu{A}}_{13} =$ | $\frac{I^{\uu{A}}_3-I^{\uu{A}}_1}{a^2-c^2}$ | $\frac{I^{\uu{A}}_3-I^{\uu{A}}_1}{a^2-c^2}$ | $\frac{I^{\uu{A}}_3-I^{\uu{A}}_1}{a^2-c^2}$ | $\frac{1}{5\,a^2}$ |
| $I^{\uu{A}}_{12} = I^{\uu{A}}_{21} =$ | $\frac{I^{\uu{A}}_2-I^{\uu{A}}_1}{a^2-b^2}$ | $\frac{I^{\uu{A}}_2-I^{\uu{A}}_1}{a^2-b^2}$ | $\frac{1}{4}\left(\frac{1}{a^2}-I^{\uu{A}}_{31} \right)$ | $\frac{1}{5\,a^2}$ |


: Components $I^{\uu{A}}_{ij}$ {#tbl-Iij .striped .hover .bordered .danger}

::: {.callout-warning} 

## Warning

Note that, for writing convenience, $I^{\uu{A}}_i$ of @tbl-Ii and $I^{\uu{A}}_{ij}$ of @tbl-Iij are here adapted from those provided in [@kellogg1929] and [@eshelby1957]: they differ by a factor of $4\pi/3$ for $I^{\uu{A}}_{ij}$ with $i\neq j$ and by $4\pi$ for the others.

:::

Components $I^{\uu{A}}_i$ and $I^{\uu{A}}_{ij}$ are alternatively given in a generic form in the following section to be expanded.

::: {.callout-note collapse=true}

## Generic expressions of $I^{\uu{A}}_i$ and $I^{\uu{A}}_{ij}$ (click for details)

::: {.panel-tabset}

## $a > b > c$

$$\begin{align}
I^{\uu{A}}_1&=\frac{a\,b\,c}{(a^2-b^2)\sqrt{a^2-c^2}}\,
\left({\cal F}-{\cal E}\right)\\
I^{\uu{A}}_3&=\frac{a\,b\,c}{(b^2-c^2)\sqrt{a^2-c^2}}\,
\left(\frac{b\sqrt{a^2-c^2}}{a\,c}-
{\cal E}\right)\\
I^{\uu{A}}_2&=1-I^{\uu{A}}_1-I^{\uu{A}}_3\\
I^{\uu{A}}_{ij}&=\frac{I^{\uu{A}}_j-I^{\uu{A}}_i}{\rho_i^2-\rho_j^2}\quad\forall\, i\neq j\in\{1,2,3\}\\
I^{\uu{A}}_{ii}&=\frac{1}{3}\left(
\frac{1}{\rho_i^2}-
\sum_{j\neq i}I^{\uu{A}}_{ij} \right) 
\quad\forall\, i\in\{1,2,3\}
\end{align}$$

## $a > b = c$ (prolate spheroid)

$$\begin{align}
I^{\uu{A}}_2=I^{\uu{A}}_3&=a\,
\frac{a\sqrt{a^2-c^2}-c^2\,\arcosh{(a/c)}}
{2\left(a^2-c^2\right)^{3/2}}\\
I^{\uu{A}}_1&=1-2\,I^{\uu{A}}_3\\
I^{\uu{A}}_{1i}=I^{\uu{A}}_{i1}&=\frac{I^{\uu{A}}_i-I^{\uu{A}}_1}{a^2-\rho_i^2}\quad
\forall\, i\in\{2,3\}\\
I^{\uu{A}}_{ij}&=\frac{1}{4}
\left(\frac{1}{c^2}-I^{\uu{A}}_{31} \right) 
\quad\forall\, i,j\in\{2,3\}\\
I^{\uu{A}}_{11}&=\frac{1}{3}
\left(\frac{1}{a^2}-2\,I^{\uu{A}}_{31} \right)
\end{align}$$

## $a = b > c$ (oblate spheroid)

$$\begin{align}
I^{\uu{A}}_1=I^{\uu{A}}_2&=c\,
\frac{a^2\,\arccos{(c/a)}-c\sqrt{a^2-c^2}}
{2\left(a^2-c^2\right)^{3/2}}\\
I^{\uu{A}}_3&=1-2\,I^{\uu{A}}_1\\
I^{\uu{A}}_{3i}=I^{\uu{A}}_{i3}&=\frac{I^{\uu{A}}_3-I^{\uu{A}}_i}{\rho_i^2-c^2}\quad
\forall\, i\in\{1,2\}\\
I^{\uu{A}}_{ij}&=\frac{1}{4}
\left(\frac{1}{a^2}-I^{\uu{A}}_{31} \right) 
\quad\forall\, i,j\in\{1,2\}\\
I^{\uu{A}}_{33}&=\frac{1}{3}
\left(\frac{1}{c^2}-2\,I^{\uu{A}}_{31} \right)
\end{align}$$

## $a = b = c$ (sphere)
$$\begin{align}
I^{\uu{A}}_1=I^{\uu{A}}_2=I^{\uu{A}}_3&=\frac{1}{3}\\
I^{\uu{A}}_{ij}&=\frac{1}{5\,a^2}\quad\forall\, i,j\in\{1,2,3\}
\end{align}$$

:::

:::

For an arbitrary ellipsoid defined by (@eq-ellipsoid), the non-zero components of $\uuuu{U}^{\uu{A}}$ and $\uuuu{V}^{\uu{A}}$ write ([@barthelemyIJSS2016], [@barthelemyIJES2020_hilltrans])
$$\begin{align}
U^{\uu{A}}_{iiii}&=\frac{3(I^{\uu{A}}_i-\rho_i^2I^{\uu{A}}_{ii})}{2} 
\quad\forall\, i\in\{1,2,3\}\\
U^{\uu{A}}_{iijj}=U^{\uu{A}}_{ijij}=U^{\uu{A}}_{ijji}&=\frac{I^{\uu{A}}_j-\rho_i^2I^{\uu{A}}_{ij}}{2} 
=\frac{I^{\uu{A}}_i-\rho_j^2I^{\uu{A}}_{ij}}{2}
\quad\forall\, i\neq j\in\{1,2,3\}
\end{align}$${#eq-Uijkl}
and
$$\begin{align}
V^{\uu{A}}_{iiii}&=I^{\uu{A}}_i\quad\forall\, i\in\{1,2,3\}\\
V^{\uu{A}}_{ijij}=V^{\uu{A}}_{ijji}&=\frac{I^{\uu{A}}_i+I^{\uu{A}}_j}{4}
\quad\forall\, i\neq j\in\{1,2,3\}
\end{align}$${#eq-Vijkl}

In the case of a spherical inclusion ($\uu{A}=\uu{1}$), note that $\uuuu{U}^{\uu{A}}$ and $\uuuu{V}^{\uu{A}}$ are simply decomposed as
$$
\uuuu{U}^{\uu{A}}=\frac{1}{3}\uuuu{J}+\frac{2}{15}\uuuu{K}
\quad\textrm{ and }\quad
\uuuu{V}^{\uu{A}}=\frac{1}{3}\uuuu{I}
$$
where $\uuuu{I}$, $\uuuu{J}$ and $\uuuu{K}$ are defined in @sec-ISO.


## Hill polarization tensor in elasticity

### General expression

A general expression of the elastic polarization tensor is derived in [@willis1977] (see also [@mura1987])
$$\begin{align}
\uuuu{P}(\uu{A},\uuuu{C})&=\frac{1}{4\pi}
\int_{\norm{\uv{\zeta}}=1}
(\uu{A}^{-1}\cdot\uv{\zeta})\sotimes
\Big((\uu{A}^{-1}\cdot\uv{\zeta})\cdot\uuuu{C}
\cdot(\uu{A}^{-1}\cdot\uv{\zeta})\Big)^{-1}
\sotimes(\uu{A}^{-1}\cdot\uv{\zeta})
\ud S_\zeta\\
&=
\frac{\det{\uu{A}}}{4\pi}
\int_{\norm{\uv{\xi}}=1}
\frac{\uv{\xi}\sotimes
(\uv{\xi}\cdot\uuuu{C}
\cdot\uv{\xi})^{-1}
\sotimes\uv{\xi}}{\norm{\uu{A}\cdot\uv{\xi}}^3}
\ud S_{\xi}
\end{align}$${#eq-Hill}
where $\uuuu{C}$ is the stiffness tensor of the reference medium.

When $\uuuu{C}$ is arbitrarily anisotropic, it is necessary to resort to numerical cubature to estimate $\uuuu{P}$ as proposed in [@ghahremani1977], [@gavazzi1990] or [@masson2008]. However in some cases of anisotropy, analytical solutions are available ([@withers1989], [@suvorov2002]). Note that the transformation technique ([@pouya2000], [@pouya2006]) allows to extend the set of available anisotropy leading to analytical Hill tensor [@barthelemyIJES2020_hilltrans]. The case of isotropic matrix is particularly developed in the next section.

### Isotropic matrix

In this section, the matrix is assumed isotropic so that its stiffness tensor writes by means of a bulk $k$ and shear $\mu$ or Lamé $\lambda$ and $\mu$ moduli or even Young modulus $E$ and Poisson ratio $\nu$ with $k=\frac{E}{3(1-2\nu)}$ and $\mu=\frac{E}{2(1+\nu)}$.
$$\begin{align}
\uuuu{C} =&  3k\uuuu{J}+2\mu\uuuu{K} =  3\lambda\uuuu{I}+2\mu\uuuu{K}\\
 & \quad\textrm{with}\quad J_{ijkl}=\frac{\delta_{ij}\delta_{kl}}{3},
I^{\uu{A}}_{ijkl}=\frac{\delta_{ik}\delta_{jl}+\delta_{il}\delta_{jk}}{2}
\textrm{ and }
\uuuu{K}=\uuuu{I}-\uuuu{J}
\end{align}$${#eq-isoC}

Introducing (@eq-isoC) in (@eq-Hill) leads to after some algebra
$$
\uuuu{P}(\uu{A},3\lambda\uuuu{I}+2\mu\uuuu{K})=
\frac{1}{\lambda+2\,\mu}
\uuuu{U}^{\uu{A}}
+\frac{1}{\mu}(\uuuu{V}^{\uu{A}}-\uuuu{U}^{\uu{A}})
$${#eq-PisoC}
where the tensors $\uuuu{U}^{\uu{A}}$ and $\uuuu{V}^{\uu{A}}$, depending only on the ellipsoidal
tensor $\uu{A}$ of (@eq-ellipsoid), are given by (@eq-Uijkl) and (@eq-Vijkl).
Note that the writing (@eq-PisoC) puts well in evidence the contributions of the shape and orientation of the ellipsoid on the one hand and the moduli of the reference medium on the other hand.

## Hill polarization tensor in conductivity

### General expression

The conductivity polarization tensor related to a conductivity tensor $\uu{K}$ and an ellipsoid defined by $\uu{A}$ is also expressed in [@willis1977] under the form
$$\begin{align}
\uu{P}(\uu{A},\uu{K})&=\frac{1}{4\pi}
\int_{\norm{\uv{\zeta}}=1}
\frac{(\uu{A}^{-1}\cdot\uv{\zeta})\sotimes(\uu{A}^{-1}\cdot\uv{\zeta})}
{(\uu{A}^{-1}\cdot\uv{\zeta})\cdot\uu{K}
\cdot(\uu{A}^{-1}\cdot\uv{\zeta})}
\ud S_\zeta\\
&=
\frac{\det{\uu{A}}}{4\pi}
\int_{\norm{\uv{\xi}}=1}
\frac{\uv{\xi}\otimes\uv{\xi}}{(\uv{\xi}\cdot\uu{K}\cdot\uv{\xi})\,\norm{\uu{A}\cdot\uv{\xi}}^3}
\ud S_{\xi}
\end{align}$${#eq-Hillcond}

### Isotropic matrix

The case of an isotropic matrix $\uu{K}=K\,\uu{1}$ is straightforward:
$$
\uu{P}(\uu{A},K\,\uu{1})=
\frac{1}{K}\,
\left(
\frac{\det{\uu{A}}}{4\pi}
\int_{\norm{\uv{\xi}}=1}
\frac{\uv{\xi}\otimes\uv{\xi}}{\norm{\uu{A}\cdot\uv{\xi}}^3}
\ud S_{\xi}\right)
=
\frac{\uu{I}^{\uu{A}}}{K}
$${#eq-Hillcondiso}
with $\uu{I}^{\uu{A}}$ defined in (@eq-tensIUV) and derived in (@eq-decI) and @tbl-Ii.

### Arbitrarily anisotropic matrix

The complete solution of the second-order Hill polarization tensor in a matrix of arbitrary has been derived in [@barthelemyTIPM2009] from a reasoning based on Green solution. However a more direct solution, based on the idea of transformation, has been detailed in [@giraudMOM2019] and is recalled here. It first relies on the idea of square-root of the conductivity tensor. As a positive definite symmetric second-order tensor $\uu{K}$, it can be diagonalized in an orthonormal frame $\left(\uu{e}^K_i\right)_{i=1,2,3}$ with strictly positive eigenvalues $\left(K_i\right)_{i=1,2,3}$ such that
$$
\uu{K}=K_1 \uv{e}^{\uu{K}}_1\otimes\uv{e}^{\uu{K}}_1 + K_2 \uv{e}^{\uu{K}}_2\otimes\uv{e}^{\uu{K}}_2 + K_3 \uv{e}^{\uu{K}}_3\otimes\uv{e}^{\uu{K}}_3
$${#eq-decK}
Its square-root is then defined by
$$
\uu{K}^{½}=\sqrt{K_1} \uv{e}^{\uu{K}}_1\otimes\uv{e}^{\uu{K}}_1 + \sqrt{K_2} \uv{e}^{\uu{K}}_2\otimes\uv{e}^{\uu{K}}_2 + \sqrt{K_3} \uv{e}^{\uu{K}}_3\otimes\uv{e}^{\uu{K}}_3
$${#eq-sqrtK}
of inverse
$$
\uu{K}^{-½}=\left(\uu{K}^{½}\right)^{-1}=\frac{1}{\sqrt{K_1}} \uv{e}^{\uu{K}}_1\otimes\uv{e}^{\uu{K}}_1 + \frac{1}{\sqrt{K_2}} \uv{e}^{\uu{K}}_2\otimes\uv{e}^{\uu{K}}_2 + \frac{1}{\sqrt{K_3}} \uv{e}^{\uu{K}}_3\otimes\uv{e}^{\uu{K}}_3
$${#eq-invsqrtK}

It follows that (@eq-Hillcond) rewrites
$$\begin{align}
\uu{P}(\uu{A},\uu{K})&=\frac{1}{4\pi}
\int_{\norm{\uv{\zeta}}=1}
\frac{(\uu{A}^{-1}\cdot\uv{\zeta})\sotimes(\uu{A}^{-1}\cdot\uv{\zeta})}
{(\uu{A}^{-1}\cdot\uv{\zeta})\cdot\uu{K}
\cdot(\uu{A}^{-1}\cdot\uv{\zeta})}
\ud S_\zeta\\
&=
\frac{1}{4\pi}
\int_{\norm{\uv{\zeta}}=1}
\frac{(\uu{A}^{-1}\cdot\uv{\zeta})\sotimes(\uu{A}^{-1}\cdot\uv{\zeta})}
{(\uu{K}^{½}\cdot\uu{A}^{-1}\cdot\uv{\zeta})\cdot\uu{1}
\cdot(\uu{K}^{½}\cdot\uu{A}^{-1}\cdot\uv{\zeta})}
\ud S_\zeta\\
&=
\uu{K}^{-½}\cdot\left(\frac{1}{4\pi}
\int_{\norm{\uv{\zeta}}=1}
\frac{(\uu{K}^{½}\cdot\uu{A}^{-1}\cdot\uv{\zeta})\sotimes(\uu{K}^{½}\cdot\uu{A}^{-1}\cdot\uv{\zeta})}
{(\uu{K}^{½}\cdot\uu{A}^{-1}\cdot\uv{\zeta})\cdot\uu{1}
\cdot(\uu{K}^{½}\cdot\uu{A}^{-1}\cdot\uv{\zeta})}
\ud S_\zeta\right)\cdot\uu{K}^{-½}\\
&=
\uu{K}^{-½}\cdot\uu{P}(\uu{A}\cdot\uu{K}^{-½},\uu{1})\cdot\uu{K}^{-½}\\
&=
\uu{K}^{-½}\cdot\uu{I}^{\uu{A}\cdot\uu{K}^{-½}}\cdot\uu{K}^{-½}
\end{align}$${#eq-Hillcondaniso}
where $\uu{I}^{\uu{A}\cdot\uu{K}^{-½}}$ is deduced from $\uu{I}^{\uu{A}}$ defined in (@eq-tensIUV) and derived in (@eq-decI) and @tbl-Ii in which the characteristic tensor of the ellipsoid $\uu{A}$ is replaced by $\uu{A}\cdot\uu{K}^{-½}$ defining a fictitious ellipsoid. Even if $\uu{A}\cdot\uu{K}^{-½}$ is not necessarily symmetric, it is pointed out that the new fictitious radii and eigenvectors are defined by adaptation of (@eq-ellipsoid) leading here to the diagonalization of $\uu{K}^{-½}\cdot\trans{\uu{A}}\cdot\uu{A}\cdot\uu{K}^{-½}$. 